# This file was generated by GoReleaser. DO NOT EDIT.
cask "bitty" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "5260887d26008997a15cad5157f0d1f39deefa046f8c886deb350cf728b80dcc"
      url "https://github.com/0xbenc/bitty/releases/download/v#{version}/bitty_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "947da9e720f476060d3bb4f3a4a13b6ab0ebe6596c9b1fb9a12cb15a69d260e8"
      url "https://github.com/0xbenc/bitty/releases/download/v#{version}/bitty_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "686af243c116f0aaaea2329e5740b5358af25070e0233d7ba95c3fed4435a183"
      url "https://github.com/0xbenc/bitty/releases/download/v#{version}/bitty_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "824c17cce6087ec311f1087cfb6bf7c97056ee50d4dd6435646258717ff5c6f6"
      url "https://github.com/0xbenc/bitty/releases/download/v#{version}/bitty_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bitty"
  desc "Set life loose in your terminal."
  homepage "https://github.com/0xbenc/bitty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bitty"
  manpage "man/bitty.1"
  bash_completion "completions/bitty.bash"
  fish_completion "completions/bitty.fish"
  zsh_completion "completions/bitty.zsh"

  # No zap stanza required

end
