# This file was generated by GoReleaser. DO NOT EDIT.
cask "bitty" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "705dbc535e81ec13bf00ef7ee0516550783f0785f3fd38e37dd58f4a68b748f7"
      url "https://github.com/0xbenc/bitty/releases/download/v#{version}/bitty_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3feab9e98c50dbfb326676991a89ebf186572181cf819e6ab9e23782c50918b3"
      url "https://github.com/0xbenc/bitty/releases/download/v#{version}/bitty_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6828012b621f44b80eb437cc1aa3284bdf4da1d52d61aeb516676f468dfea987"
      url "https://github.com/0xbenc/bitty/releases/download/v#{version}/bitty_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7a4bf65e08c0469dc2d09047a280cb64ab8fc33d8c8dfefe02a7cf6e1cc47911"
      url "https://github.com/0xbenc/bitty/releases/download/v#{version}/bitty_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bitty"
  desc "Set life loose in your terminal."
  homepage "https://github.com/0xbenc/bitty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bitty"
  manpage "man/bitty.1"
  bash_completion "completions/bitty.bash"
  fish_completion "completions/bitty.fish"
  zsh_completion "completions/bitty.zsh"

  # No zap stanza required

end
