# This file was generated by GoReleaser. DO NOT EDIT.
cask "dangit" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "094b65ac7e408466bee35b18776fa3d97f324c387ef2351e804a6f925ecc1221"
      url "https://github.com/0xbenc/dangit/releases/download/v#{version}/dangit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "525fa64557bb469b674941e748acfe5779f0f371b0177551749cb0e1e8a93d8e"
      url "https://github.com/0xbenc/dangit/releases/download/v#{version}/dangit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "19eff083f3976a08b15f0165e4f8c9d61efa0ff308ef4fc992b7158d9d159d50"
      url "https://github.com/0xbenc/dangit/releases/download/v#{version}/dangit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1e522a881fd792d30bd996a20fe685728cb338ee90c725f5497d94d8c8d1cb8e"
      url "https://github.com/0xbenc/dangit/releases/download/v#{version}/dangit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dangit"
  desc "Find git repos with unfinished work — uncommitted, unpushed, or behind."
  homepage "https://github.com/0xbenc/dangit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dangit"
  manpage "man/dangit.1"
  bash_completion "completions/dangit.bash"
  fish_completion "completions/dangit.fish"
  zsh_completion "completions/dangit.zsh"

  # No zap stanza required

end
