# This file was generated by GoReleaser. DO NOT EDIT.
cask "dangit" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "1781869ae6d94c379baedb1a4021fa218033bd0ef729f6adc305da1d66f5dd49"
      url "https://github.com/0xbenc/dangit/releases/download/v#{version}/dangit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "67f01d9790691b90c1b722bbf0b82c1a7a31e7a2924cd1dbf21eb849ffbf818d"
      url "https://github.com/0xbenc/dangit/releases/download/v#{version}/dangit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "adafc4d9d6ecc561ae1b186b5ecf7d08b56430c1414e07207f62dc01023cf530"
      url "https://github.com/0xbenc/dangit/releases/download/v#{version}/dangit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "99b0f6e0643f5932eb099d0f29234858d28ee264147c3760936e94b9e19f4433"
      url "https://github.com/0xbenc/dangit/releases/download/v#{version}/dangit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dangit"
  desc "Find git repos with unfinished work — uncommitted, unpushed, or behind."
  homepage "https://github.com/0xbenc/dangit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dangit"
  manpage "man/dangit.1"
  bash_completion "completions/dangit.bash"
  fish_completion "completions/dangit.fish"
  zsh_completion "completions/dangit.zsh"

  # No zap stanza required

end
