# This file was generated by GoReleaser. DO NOT EDIT.
cask "dangit" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "6e987076a14c84c85bcfe28a8160627877029dac8d6870b2602fc7fa9a24d045"
      url "https://github.com/0xbenc/dangit/releases/download/v#{version}/dangit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5a939b3b11d51de2f91f9d989322efe5b7777c897bbc84d5bb0ddabcdaf101a6"
      url "https://github.com/0xbenc/dangit/releases/download/v#{version}/dangit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d8c6c0baedbb30313f61d97bcf6cd7bdcc4412edfa09178beab47c4af9948206"
      url "https://github.com/0xbenc/dangit/releases/download/v#{version}/dangit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "61ea1f066a9e22d90eaa01adc5ffc17d85970dc111bcbdc3f60eeac2bb4dd58c"
      url "https://github.com/0xbenc/dangit/releases/download/v#{version}/dangit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dangit"
  desc "Find git repos with unfinished work — uncommitted, unpushed, or behind."
  homepage "https://github.com/0xbenc/dangit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dangit"
  manpage "man/dangit.1"
  bash_completion "completions/dangit.bash"
  fish_completion "completions/dangit.fish"
  zsh_completion "completions/dangit.zsh"

  # No zap stanza required

end
