# This file was generated by GoReleaser. DO NOT EDIT.
cask "passage" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "6d326d818c0f6bf4bfdede82aed9f676f3aa12933d945dfd3fccb1c8f886c0ec"
      url "https://github.com/0xbenc/passage/releases/download/v#{version}/passage_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3c9e92cb7e5d3573666fefd8d74c2194256115b8a6fcc03f551476ab294eae32"
      url "https://github.com/0xbenc/passage/releases/download/v#{version}/passage_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ed0f393db13c3a8270973cd962b2a6640bd4559b7235f25c98f162a07ae75b2b"
      url "https://github.com/0xbenc/passage/releases/download/v#{version}/passage_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "19f6205224b70421623dee45f284f4ccccafa8bf51bc1a5370ef851d650e6d40"
      url "https://github.com/0xbenc/passage/releases/download/v#{version}/passage_#{version}_linux_arm64.tar.gz"
    end
  end

  name "passage"
  desc "Terminal UI for GNU Pass with pins, recents, and native TOTP."
  homepage "https://github.com/0xbenc/passage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "passage"
  manpage "man/passage.1"
  bash_completion "completions/passage.bash"
  fish_completion "completions/passage.fish"
  zsh_completion "completions/passage.zsh"

  # No zap stanza required

end
