# This file was generated by GoReleaser. DO NOT EDIT.
cask "passage" do
  version "0.8.4"

  on_macos do
    on_intel do
      sha256 "a0f542bbdd7d879393ae7d0417714e1aae1b5ce17e44855f74c1190cd0fe5d2d"
      url "https://github.com/0xbenc/passage/releases/download/v#{version}/passage_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2db5dbede5c3967269a6d6a53c6fc261243f3d9609aecda27fde2aa59709f06a"
      url "https://github.com/0xbenc/passage/releases/download/v#{version}/passage_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "65c1bf0d30f75671044d26f11decc68d2cf120719ca1c8e678e028bb647142c2"
      url "https://github.com/0xbenc/passage/releases/download/v#{version}/passage_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ffe23131e12233347114d70bd0dbbbce98324c5be52b6e43e8e1e8ca2ca930b9"
      url "https://github.com/0xbenc/passage/releases/download/v#{version}/passage_#{version}_linux_arm64.tar.gz"
    end
  end

  name "passage"
  desc "Terminal UI for GNU Pass with pins, recents, and native TOTP."
  homepage "https://github.com/0xbenc/passage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "passage"
  manpage "man/passage.1"
  bash_completion "completions/passage.bash"
  fish_completion "completions/passage.fish"
  zsh_completion "completions/passage.zsh"

  # No zap stanza required

end
