# This file was generated by GoReleaser. DO NOT EDIT.
cask "passage" do
  version "0.9.1"

  on_macos do
    on_intel do
      sha256 "ac12b6e51ce78f87830301718e960a310ca490613665ace289d452cb4fafec64"
      url "https://github.com/0xbenc/passage/releases/download/v#{version}/passage_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4cc31d8570a88a2b4696dd46e1664562d5f0317e56192799d32a5f4af5c86274"
      url "https://github.com/0xbenc/passage/releases/download/v#{version}/passage_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "77049578257f97f52e5865b835aa7b73b57eb74f63d2ac7fdc95d2256675ed5a"
      url "https://github.com/0xbenc/passage/releases/download/v#{version}/passage_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8f7d2e619a080ebc473b68113245723664a1487595e0e30bc8ac3f9e3e8632af"
      url "https://github.com/0xbenc/passage/releases/download/v#{version}/passage_#{version}_linux_arm64.tar.gz"
    end
  end

  name "passage"
  desc "Terminal UI for GNU Pass with pins, recents, and native TOTP."
  homepage "https://github.com/0xbenc/passage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "passage"
  manpage "man/passage.1"
  bash_completion "completions/passage.bash"
  fish_completion "completions/passage.fish"
  zsh_completion "completions/passage.zsh"

  # No zap stanza required

end
