# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssherpa" do
  version "1.5.0"

  on_macos do
    on_intel do
      sha256 "93b99db956a3a5fb976a4376e369bc30ab257a2bd14cc07ebdb100bcd28fc0a3"
      url "https://github.com/0xbenc/ssherpa/releases/download/v#{version}/ssherpa_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7e11cf4d42f54779d3140526f2cbe629815e308733235fa1761246bf6d2e1a7a"
      url "https://github.com/0xbenc/ssherpa/releases/download/v#{version}/ssherpa_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1a4080dab1f833688397b8a1f35e336927390e24f5a6efdc63abf7af572697c8"
      url "https://github.com/0xbenc/ssherpa/releases/download/v#{version}/ssherpa_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "032cf30178c1911e8864839f3440782beebfe18c8cd4d2d53217b89e3d11f732"
      url "https://github.com/0xbenc/ssherpa/releases/download/v#{version}/ssherpa_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ssherpa"
  desc "A terminal UI for the SSH config you already have, with supervised sessions."
  homepage "https://github.com/0xbenc/ssherpa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssherpa"
  manpage "man/ssherpa.1"
  bash_completion "completions/ssherpa.bash"
  fish_completion "completions/ssherpa.fish"
  zsh_completion "completions/ssherpa.zsh"

  # No zap stanza required

end
