# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssherpa" do
  version "1.6.8"

  on_macos do
    on_intel do
      sha256 "bf7358f479073708099861b9c56396362c5e840a6966a9c053dc0d4d274ada24"
      url "https://github.com/0xbenc/ssherpa/releases/download/v#{version}/ssherpa_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dfbfd91f88538904268fdfce4261c036eeb3ed68c8eb59251a15e9c8751e8c1a"
      url "https://github.com/0xbenc/ssherpa/releases/download/v#{version}/ssherpa_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a64aecb32e793d38a6f91bdc092646578dea4a329075c556fbc47bb08759fc8f"
      url "https://github.com/0xbenc/ssherpa/releases/download/v#{version}/ssherpa_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d67cb49620c3d14d83721d43fc72450909edad8ad76d518c8f6380ac02bdb858"
      url "https://github.com/0xbenc/ssherpa/releases/download/v#{version}/ssherpa_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ssherpa"
  desc "A terminal UI for the SSH config you already have, with supervised sessions."
  homepage "https://github.com/0xbenc/ssherpa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssherpa"
  manpage "man/ssherpa.1"
  bash_completion "completions/ssherpa.bash"
  fish_completion "completions/ssherpa.fish"
  zsh_completion "completions/ssherpa.zsh"

  # No zap stanza required

end
