# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssherpa" do
  version "1.6.12"

  on_macos do
    on_intel do
      sha256 "c7cf95277a68a21166d802186ee59668fe5bd5bca4da226f33415e5ed4aea717"
      url "https://github.com/0xbenc/ssherpa/releases/download/v#{version}/ssherpa_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bbbd159d95ee80a6dfb9bdd94bf6d4ea42d50feec554b71531d01aecc2f5c321"
      url "https://github.com/0xbenc/ssherpa/releases/download/v#{version}/ssherpa_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9a311ffa378326d48f69c9402547a1dfa877d4b30df6127046340816454a24a3"
      url "https://github.com/0xbenc/ssherpa/releases/download/v#{version}/ssherpa_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "de813953e2c4b0eae4a53f7cd40dde20d47320635b7271ba902ea66968d372a8"
      url "https://github.com/0xbenc/ssherpa/releases/download/v#{version}/ssherpa_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ssherpa"
  desc "A terminal UI for the SSH config you already have, with supervised sessions."
  homepage "https://github.com/0xbenc/ssherpa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssherpa"
  manpage "man/ssherpa.1"
  bash_completion "completions/ssherpa.bash"
  fish_completion "completions/ssherpa.fish"
  zsh_completion "completions/ssherpa.zsh"

  # No zap stanza required

end
